data = {
	lowFamilyList: {
		"total": 39510,
		"success": true,
		"message": "",
		"results": [{
			"zpyy_q_yzsfzdlbz": null,
			"qyxzc": "ZCJG201707131704340116",
			"zyrllx": "01",
			"gdmj": 5,
			"hzmz": "01",
			"sfjrnmzyhzs": "0",
			"yssfkn": "0",
			"qyxs": "ZJZD201707131547250003",
			"zpyy_q_yjttjlh": null,
			"id": "1000004391626482016",
			"wfid": null,
			"khyh": {},
			"qyxz": "ZCJG201707131659280103",
			"fwfgzbt": 0,
			"whrid": null,
			"lxdh": null,
			"hzjkzk": "02",
			"ldmj": 0,
			"fjs": 0,
			"hzzjhm": "132523192701251120",
			"sftshyd": "1",
			"yczgljl": 1.5,
			"filegrpid": null,
			"smmj": 0,
			"sfbqh": null,
			"zpyy_q_yqzj": null,
			"yhzh": null,
			"wfhandler": null,
			"azd": null,
			"wfinst": null,
			"fjybfj": 0,
			"hzxb": "女",
			"fsnhbt": 0,
			"sftscyd": null,
			"exproperty": null,
			"hzpkhlx": null,
			"ywwscs": "1",
			"zpyy_q_yqs": null,
			"flszhzb": 0,
			"fcyjb": 0,
			"tghlmj": 0,
			"key": null,
			"sfdsznh": "0",
			"hznl": 90,
			"hzwhcd": "02",
			"fdbbxbx": 0,
			"zpyy_q_yqjs": null,
			"btpyy": null,
			"yxgkmj": 0,
			"lgmj": 0,
			"qyzrc": null,
			"bqfs": null,
			"rhllx": "02",
			"qtzyxsr": 0,
			"bqknczkn_bqhshmzl": null,
			"qyds": "ZJZD201707131547090002",
			"zpyy_q_yqtd": null,
			"wpid": null,
			"zyzpyy": "01",
			"bqknczkn_qfzj": null,
			"mcdmj": 0,
			"fjybt": 0,
			"hszbz": "0",
			"sfzc": 0,
			"wfawaiter": null,
			"bqknczkn_qt": null,
			"pkhjc": null,
			"hzzzmm": "13",
			"jtjyfyzc": 0,
			"bhksx": "04",
			"tpqk": null,
			"fylj": 0,
			"zpyy_q_yz": null,
			"ftghlbt": 0,
			"errmessage": null,
			"zpyy_q_qt": null,
			"fdbj": 0,
			"zpyy_q_yx": null,
			"hzldjl": "04",
			"dbj": 2160,
			"rjcsr": 3402,
			"scjyxsr": 840,
			"nd": 2016,
			"hzxm": "刘凤英",
			"ydb": null,
			"jtswzsk": 0,
			"qtscjyxzc": 0,
			"sfjls": "0",
			"zpyy_q_yh": null,
			"zpyy_q_yb": "04",
			"qyss": "ZJZD201707131546410001",
			"fc": null,
			"zpyy_q_yc": null,
			"sfsnh": "0",
			"jhsyj": 0,
			"whr": null,
			"stbcj": 402,
			"ylbzj": 960,
			"scjyxzc": 0,
			"zyxsr": 2562,
			"fp": null,
			"edittype": 0,
			"sbbz": null,
			"bqknczkn_bqhzbdgz": null,
			"zpyy_q_yqldl": null,
			"ccxsr": 0,
			"yssfaq": "1",
			"fyljz": 0,
			"whsj": "27 Jul 2017 07:32:40 GMT",
			"gzxsr": 0,
			"sjzt": null,
			"fwbj": 0,
			"azfs": null,
			"zfmj": 45,
			"ywzf": null,
			"bfdx": null,
			"fjbylbx": 0,
			"wbj": 0
		}]
	}
}

//data={
//	//自然村列表	
//	"natural":{
//	    "total": 600,
//	    "success": true,
//	    "message": "",
//	    "results": [
//	        {
//	            "whr": null,
//	            "fnrks": 122,
//	            "wpid": null,
//	            "zhs": 105,
//	            "dxzcjl": 1,
//	            "wfawaiter": null,
//	            "wfhandler": null,
//	            "fp": null,
//	            "wfinst": null,
//	            "dxzcsftlql": "1",
//	            "sftscyd": "1",
//	            "edittype": 0,
//	            "lsxzc": "二台子村",
//	            "exproperty": null,
//	            "wbrks": 2,
//	            "ldlrs": 131,
//	            "smmzrks": 0,
//	            "zrks": 267,
//	            "id": "182875",
//	            "wfid": null,
//	            "sftkd": "1",
//	            "fzr": "宋桂彬",
//	            "whsj": "27 Jul 2017 06:59:37 GMT",
//	            "wbhs": 2,
//	            "whrid": null,
//	            "lxdh": "13663330678",
//	            "pkrks": 0,
//	            "wcwgrs": 58,
//	            "h13a": 0,
//	            "dbhs": 20,
//	            "zrcmc": "二台子村",
//	            "zh": "3",
//	            "fjs": 0,
//	            "sftshyd": "1",
//	            "pkhs": 0,
//	            "hjrks": 0,
//	            "dbrks": 26,
//	            "nd": 2016,
//	            "cjrks": 8,
//	            "fc": null,
//	            "filegrpid": null
//	        }
//	    ]
//	}
//	//自然村编辑
//		{
//	    "total": 0,
//	    "success": true,
//	    "message": "",
//	    "results": {
//	        "whr": null,
//	        "fnrks": 122,
//	        "wpid": null,
//	        "zhs": 105,
//	        "dxzcjl": 1,
//	        "wfawaiter": null,
//	        "wfhandler": null,
//	        "fp": null,
//	        "wfinst": null,
//	        "dxzcsftlql": "1",
//	        "sftscyd": "1",
//	        "edittype": 0,
//	        "lsxzc": "ZCJG201707131730450188",
//	        "exproperty": null,
//	        "ldlrs": 131,
//	        "wbrks": 2,
//	        "smmzrks": 0,
//	        "zrks": 267,
//	        "id": "182875",
//	        "wfid": null,
//	        "sftkd": "否",
//	        "fzr": "宋桂彬",
//	        "whsj": "27 Jul 2017 12:35:18 GMT",
//	        "wbhs": 2,
//	        "whrid": null,
//	        "lxdh": "13663330678",
//	        "pkrks": 0,
//	        "wcwgrs": 58,
//	        "dbhs": 20,
//	        "h13a": 0,
//	        "zrcmc": "ZCJG201707141441060579",
//	        "zh": "3",
//	        "fjs": 0,
//	        "sftshyd": "1",
//	        "pkhs": 0,
//	        "dbrks": 26,
//	        "hjrks": 0,
//	        "nd": 2016,
//	        "cjrks": 8,
//	        "fc": null,
//	        "filegrpid": null
//	    }
//	}
//}
//
//
////data={
////	'naturalVillage':{
////		'hhhh':123
////	}
////}