lowFamilyInfoModel = {
	baseInfo_model: {
		id: "",
		qyxz: "",
		qyxzc: "",
		qyzrc: "",
		lxdh: "",
		khyh: "",
		yhzh: "",
		bhksx: "",
		sfjls: "",
		sfdsznh: "",
		sfsnh: "",
		tpqk: "",
	},
	assistEffect_model: {
		//帮扶成效
		fjybfj: "",
		fdbj: "",
		fwbj: "",
		fylj: "",
		fwfgzbt: "",
		fjybt: "",
		fjbylbx: "",
		fdbbxbx: "",
		fyljz: "",
		fsnhbt: "",
		flszhzb: "",
		ftghlbt: "",
		fcyjb: "",
	},
	familyInfo_model: [] //家庭成员
		,
	assistPerson_model: [] //帮扶责任人
		,
	income_model: {
		//收入
		gzxsr: "",
		scjyxsr: "",
		ccxsr: "",
		zyxsr: "",
		jhsyj: "",
		dbj: "",
		wbj: "",
		ylbzj: "",
		stbcj: "",
		qtzyxsr: "",
		jtswzsk: "",
		rjcsr: "",
		scjyxzc: "",
		jtjyfyzc: "",
		sfzc: "",
		qtscjyxzc: "",
	},
	lifeCondition_model: {
		//生产生活方式
		gdmj: "",
		yxgkmj: "",
		ldmj: "",
		tghlmj: "",
		lgmj: "",
		mcdmj: "",
		smmj: "",
		sftscyd: "",
		yczgljl: "",
		rhllx: "",
		zfmj: "",
		sftshyd: "",
		yssfkn: "",
		yssfaq: "",
		zyrllx: "",
		sfjrnmzyhzs: "",
		ywwscs: "",
	},
	povertyCauses_model: {
		//贫困原因
		zyzpyy: "",
		zpyy_q_yb: "",
		zpyy_q_yc: "",
		zpyy_q_yx: "",
		zpyy_q_yz: "",
		zpyy_q_yqtd: "",
		zpyy_q_yqs: "",
		zpyy_q_yqjs: "",
		zpyy_q_yqzj: "",
		zpyy_q_yqldl: "",
		zpyy_q_yjttjlh: "",
		zpyy_q_yzsfzdlbz: "",
	},
	plantRelocation_model: {
		//易地搬迁
		sfbqh: "",
		bqfs: "",
		azfs: "",
		azd: "",
		bqknczkn_qfzj: "",
		bqknczkn_bqhzbdgz: "",
		bqknczkn_bqhshmzl: "",
		bqknczkn_qt: "",
	}
};